[package]
name = "zork"
version = "0.3.1"
edition = "2021"

[lib]
name = "zork"
path = "src/lib.rs"

[[bin]]
name = "zork"
path = "src/main.rs"

[dependencies]
toml = "0.5.10"
serde = { version = "1.0.138", features = ["derive"] }