name: windows-make-installer

on:
  push:
  pull_request:

jobs:
  Building-Installer:
    runs-on: windows-latest
    steps:
      - name: Make enviromment Python and PyInstaller
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
        run: python -m pip install pyinstaller

      - name: Building exe
        run: | 
          echo "bad run"

      - name: Building the installer
        run: |
          "%programfiles(x86)%\Inno Setup 6\iscc.exe" "FreenetInstall_InnoSetup.iss"
        shell: cmd
        